###
GET http://localhost:5003



### register the user
POST http://localhost:5003/auth/register
Content-Type: application/json

{
    "username":"Faizan@gmail",
    "password":"123123123"
}



### login a user
POST http://localhost:5003/auth/login
Content-Type: application/json

{
    "username":"Faizan@gmail",
    "password":"123123123"
}


